'use client'
import { Button } from "@/components/ui/button";
import { SummarySlide } from "@/types/summary";
import { Download } from "lucide-react";
import { useMemo } from "react";

export default function DownloadSummaryButton({
    summaryText,
    title,
    fileName,
    createdAt
}: {
    summaryText: SummarySlide[];
    title: string;
    fileName: string;
    createdAt: Date;
}){

    const summary  = useMemo(() => {
        if(summaryText.length === 0){
            return null;
        }
        return summaryText.map((s) => {
            return [`### ${s.heading}`, ...s.points].join('\n')
        }).join('\n\n');
    },[
        summaryText,
        title,
        fileName,
        createdAt
    ])

    const handleDownload = () => {
        const blobData = `# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}

${summary}

Original File: ${fileName}
Generated by Snipnote
Downloaded on: ${new Date().toLocaleDateString()}
        `

        const blob = new Blob([blobData],{type:'text/plain'})
        const blobUrl = URL.createObjectURL(blob)

        const downloadLink = document.createElement('a')
        downloadLink.href = blobUrl
        downloadLink.download = `Summary ${title.replace(/[^a-z0-9]/gi,'_')}.txt`;
        document.body.appendChild(downloadLink)
        downloadLink.click()

        document.body.removeChild(downloadLink)
        URL.revokeObjectURL(blobUrl);

    }
    return (
        <Button
        size='sm'
        onClick={handleDownload}
        className="h-8 px-3 text-rose-600 hover:text-rose-700 hover:bg-rose-50 bg-rose-100"
        >
            <Download className="h-4 w-4 mr-1" />
            Download Summary
        </Button>
    );
}